# Generated by Django 5.2 on 2025-04-22 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workspace', '0002_remove_list_card'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('MEMBERWORKSPACE', 'MemberWorkspace'), ('WORKSPACEOWN', 'WorkspaceOwn')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Workspace.workspace')),
            ],
        ),
        migrations.AddField(
            model_name='workspace',
            name='member',
            field=models.ManyToManyField(related_name='memberworkspaces', through='Workspace.WorkspaceMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
