# Generated by Django 5.2 on 2025-04-28 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Workspace', '0003_workspacemember_workspace_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='owner',
        ),
    ]
