# Generated by Django 5.2 on 2025-05-05 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_account_is_staff'),
        ('Workspace', '0004_remove_workspace_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='member',
            field=models.ManyToManyField(related_name='memberworkspaces', through='Workspace.WorkspaceMember', to='Account.userprofile'),
        ),
        migrations.AlterField(
            model_name='workspacemember',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MEMBERWORKSPACE', 'MemberWorkspace'), ('WORKSPACEOWN', 'WorkspaceOwn')], default='WORKSPACEOWN', max_length=50),
        ),
        migrations.AlterField(
            model_name='workspacemember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.userprofile'),
        ),
    ]
