# Generated by Django 5.2 on 2025-05-22 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workspace', '0005_alter_workspace_member_alter_workspacemember_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listcard', to='Workspace.list'),
        ),
        migrations.AlterField(
            model_name='list',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boardlists', to='Workspace.board'),
        ),
    ]
