# Generated by Django 5.2 on 2025-05-22 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_alter_userprofile_user'),
        ('Workspace', '0006_alter_card_list_alter_list_board'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workspacemember',
            unique_together={('workspace', 'user')},
        ),
    ]
