# Generated by Django 5.2 on 2025-05-23 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Workspace', '0007_alter_workspacemember_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='card',
            unique_together={('name', 'list')},
        ),
    ]
