# Generated by Django 5.2 on 2025-05-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workspace', '0008_rename_title_card_name_alter_card_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='tasks',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
