# Generated by Django 5.2 on 2025-05-23 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workspace', '0009_card_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='tasks',
            field=models.JSONField(blank=True, default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listcard', to='Workspace.list'), null=True),
        ),
    ]
