# Generated by Django 5.2 on 2025-05-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workspace', '0011_alter_card_list_alter_card_name_alter_card_tasks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='list',
            new_name='listCard',
        ),
        migrations.AlterUniqueTogether(
            name='card',
            unique_together={('name', 'listCard')},
        ),
        migrations.AlterField(
            model_name='card',
            name='tasks',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
