# Generated by Django 5.2 on 2025-05-24 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Workspace', '0012_rename_list_card_listcard_alter_card_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='list',
            unique_together=set(),
        ),
    ]
