# Generated by Django 5.2 on 2025-05-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workspace', '0013_alter_list_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='tasks',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
