# Generated by Django 5.2 on 2025-05-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workspace', '0014_alter_card_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='index',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
